language: android
android:
  components:
    - build-tools-21.1.1
    - android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script: ./gradlew clean build